### ISSUE TITLE
Pull "Other" button code into core

### ISSUE THREAD

**Issue by mjumbewu** [poepublic/shareabouts-bikesharela#13]
Also add documentation:
### Conditional Fields

In your form, you can make certain fields conditional on the value of another field. Any field that you want to appear conditionally, add the following attributes in your _config.yml_:

``` yml
conditional:
  - choice-name: <name of the field to track>
  - choice-value: <value of the tracked field that will make this field visible>
```

If you override the HTML template for the form, you can use the following `data-` attributes  on any element that should be shown conditionally instead:
- `data-choice-name`: The name of the field that you want to track
- `data-choice-value`: The value of the tracked field that will make the conditional field visible
